# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89f04ce2d51c6e2ce7bc20f35f5e54f0ec5dde7a88c49aa450a1c163df2ba35cfb8f572dbd9dbce217cbf276f46bce3cacad76635f39448787914ef86415244c

test:
  secret_key_base: 1f001cfeed7ac1ddd7757728b50e8d0a9c48ae7586072d661e6a0b696831373fa9f51da3f5ecc4aa1225659fd98b327d79f6ceea2fb8b882fc3511aeccc7303a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
